# Generated by Django 4.1.5 on 2023-03-13 17:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Ads',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('brand', models.CharField(max_length=50, verbose_name='Марка')),
                ('mode', models.CharField(max_length=50, verbose_name='Модель')),
                ('year', models.IntegerField()),
                ('dvig', models.CharField(max_length=50, verbose_name='Марка')),
                ('mileage', models.IntegerField()),
                ('rule', models.CharField(max_length=50, verbose_name='Марка')),
                ('full_text', models.TextField(verbose_name='Инфо')),
                ('created_ad', models.DateTimeField(auto_now_add=True, verbose_name='Дата публикации')),
                ('updated_ad', models.DateTimeField(auto_now=True, verbose_name='Дата обвновления')),
                ('photo', models.ImageField(upload_to='photos/%Y/%m/%d/')),
                ('is_published', models.BooleanField(default=True)),
            ],
        ),
    ]
