# Generated by Django 4.1.5 on 2023-03-20 05:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_category_alter_ads_options_ads_category'),
    ]

    operations = [
        migrations.CreateModel(
            name='Mark',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(db_index=True, max_length=50, verbose_name='Марки')),
            ],
        ),
        migrations.RemoveField(
            model_name='ads',
            name='brand',
        ),
        migrations.AlterField(
            model_name='ads',
            name='category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='main.category', verbose_name='Категория'),
        ),
        migrations.AlterField(
            model_name='ads',
            name='dvig',
            field=models.CharField(max_length=50, verbose_name='Тип двигателя'),
        ),
        migrations.AlterField(
            model_name='ads',
            name='rule',
            field=models.CharField(max_length=50, verbose_name='Расположение руля'),
        ),
        migrations.AddField(
            model_name='ads',
            name='marks',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='main.mark', verbose_name='Марки'),
        ),
    ]
