# Generated by Django 4.1.5 on 2023-03-20 19:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_alter_mark_options_remove_ads_mode_markmodel_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Engine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, verbose_name='Тип двигателя')),
            ],
            options={
                'verbose_name': 'Двигатель',
                'verbose_name_plural': 'Двигатели',
            },
        ),
        migrations.CreateModel(
            name='Rudder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, verbose_name='Расположение руля')),
            ],
            options={
                'verbose_name': 'Руль',
                'verbose_name_plural': 'Рули',
            },
        ),
        migrations.AlterModelOptions(
            name='markmodel',
            options={'verbose_name': 'Модель', 'verbose_name_plural': 'Модели'},
        ),
    ]
