# Generated by Django 4.1.5 on 2023-03-20 19:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_engine_rudder_alter_markmodel_options'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Rudder',
        ),
        migrations.RemoveField(
            model_name='ads',
            name='dvig',
        ),
        migrations.AddField(
            model_name='ads',
            name='engine',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='main.engine', verbose_name='Двигатели'),
        ),
    ]
