# Generated by Django 4.1.5 on 2023-03-20 19:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_delete_rudder_remove_ads_dvig_ads_engine'),
    ]

    operations = [
        migrations.CreateModel(
            name='Rudder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, verbose_name='Расположение руля')),
            ],
            options={
                'verbose_name': 'Руль',
                'verbose_name_plural': 'Рули',
            },
        ),
        migrations.RemoveField(
            model_name='ads',
            name='rule',
        ),
        migrations.AddField(
            model_name='ads',
            name='rudder',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='main.rudder', verbose_name='Рули'),
        ),
    ]
