# Generated by Django 4.1.5 on 2023-03-27 03:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_rudder_remove_ads_rule_ads_rudder'),
    ]

    operations = [
        migrations.AddField(
            model_name='ads',
            name='price',
            field=models.IntegerField(null=True, verbose_name='Цена'),
        ),
        migrations.AlterField(
            model_name='ads',
            name='mileage',
            field=models.IntegerField(verbose_name='Пробег'),
        ),
        migrations.AlterField(
            model_name='ads',
            name='year',
            field=models.IntegerField(verbose_name='Год'),
        ),
    ]
